from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

class DocumentStatus(str, Enum):
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    VIDEO_READY = "video_ready"

class DocumentBase(BaseModel):
    filename: str
    file_url: Optional[str] = None
    extracted_text: Optional[str] = None
    status: DocumentStatus = DocumentStatus.PROCESSING
    page_count: Optional[int] = 0

class DocumentCreate(DocumentBase):
    pass

class DocumentResponse(DocumentBase):
    id: str
    user_id: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

class SummaryDepth(str, Enum):
    QUICK = "quick"
    DEEP = "deep"

class SummaryCreate(BaseModel):
    document_id: str
    depth: SummaryDepth = SummaryDepth.QUICK

class SummaryResponse(BaseModel):
    id: str
    document_id: str
    sections: List[Dict[str, Any]]
    depth: SummaryDepth
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

class QuizQuestionResponse(BaseModel):
    id: str
    document_id: str
    section_index: int
    question_text: str
    options: List[str]
    correct_answer_index: int
    page_reference: Optional[int] = None

    model_config = ConfigDict(from_attributes=True)

class QuizAttemptCreate(BaseModel):
    question_id: str
    selected_answer: int
    confidence_score: int = Field(ge=1, le=5)

class QuizAttemptResponse(BaseModel):
    id: str
    user_id: str
    question_id: str
    selected_answer: int
    is_correct: bool
    confidence_score: int
    answered_at: datetime

    model_config = ConfigDict(from_attributes=True)

class ReviewItemResponse(BaseModel):
    id: str
    user_id: str
    question_id: str
    last_reviewed: datetime
    ease_factor: float
    interval: int
    next_review_date: datetime

    model_config = ConfigDict(from_attributes=True)

class StudyPlanCreate(BaseModel):
    exam_date: datetime
    documents: Optional[List[str]] = []

class StudyPlanResponse(BaseModel):
    id: str
    user_id: str
    exam_date: datetime
    schedule: List[Dict[str, Any]]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

class ExamProfileResponse(BaseModel):
    id: str
    exam_name: str
    sections: List[Dict[str, Any]]
    question_types: List[str]
    time_limit: Optional[int] = None
    disclaimer_text: str

    model_config = ConfigDict(from_attributes=True)

class UserUsageResponse(BaseModel):
    id: str
    user_id: str
    month: int
    year: int
    video_generations_used: int
    summary_generations_used: int

    model_config = ConfigDict(from_attributes=True)

class SharedLinkCreate(BaseModel):
    document_id: str
    expires_in_days: Optional[int] = 7

class SharedLinkResponse(BaseModel):
    id: str
    document_id: str
    share_id: str
    expires_at: datetime
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

class AIContentDisclaimer(BaseModel):
    disclaimer: str = "This content was generated by AI locally. Please verify important information with primary source materials."
