import uuid
from typing import Any, Dict, List, Optional
from database import supabase
from models import SummaryDepth
from services.ollama_service import ollama_service

SUMMARY_DISCLAIMER = "Disclaimer: This summary was generated by AI locally. Please verify important details with source materials."

# In-memory summaries cache for unit tests/local fallback
_in_memory_summaries: List[Dict[str, Any]] = []

class SummaryService:
    """Service for generating and storing AI summaries using Ollama and FAISS RAG indexing."""

    async def check_user_summary_quota(self, user_id: str) -> bool:
        """Verifies if user has remaining summary generations for current month (max 50/month)."""
        try:
            res = supabase.table("user_usage").select("summary_generations_used").eq("user_id", user_id).execute()
            if res.data and res.data[0].get("summary_generations_used", 0) >= 50:
                return False
        except Exception:
            pass
        return True

    async def increment_summary_usage(self, user_id: str) -> None:
        """Increments summary_generations_used counter for user in user_usage table."""
        try:
            res = supabase.table("user_usage").select("summary_generations_used").eq("user_id", user_id).execute()
            if res.data:
                curr = res.data[0].get("summary_generations_used", 0)
                supabase.table("user_usage").update({"summary_generations_used": curr + 1}).eq("user_id", user_id).execute()
        except Exception:
            pass

    async def generate_summary_for_text(self, document_id: str, text: str, depth: str = "standard") -> Dict[str, Any]:
        """
        Generates structured summary using Ollama LLM based on depth level.
        Output format: {sections: [{title, bullets: [{text, page_number}]}]}
        """
        if depth == "quick":
            prompt_depth_instructions = "Generate a concise summary. Create 2-4 sections, with 2-3 concise bullet points per section."
            bullets_per_sec = "2-3"
        elif depth == "deep":
            prompt_depth_instructions = "Generate an in-depth comprehensive summary. Create 4-10 sections, with 8-12 detailed bullet points per section."
            bullets_per_sec = "8-12"
        else: # standard
            prompt_depth_instructions = "Generate a balanced structured summary. Create 3-8 sections, with 3-6 bullet points per section."
            bullets_per_sec = "3-6"

        prompt = (
            f"Analyze the following document text and provide a structured JSON summary.\n"
            f"Depth Mode: {depth}\n"
            f"Instructions: {prompt_depth_instructions}\n"
            f"JSON Output Format Requirements:\n"
            f"Return a JSON object with a single key 'sections' containing a list of section objects:\n"
            f"{{\n"
            f'  "sections": [\n'
            f'    {{\n'
            f'      "title": "Section Title",\n'
            f'      "bullets": [\n'
            f'        {{"text": "Key takeaway point", "page_number": 1}}\n'
            f'      ]\n'
            f'    }}\n'
            f'  ]\n'
            f"}}\n"
            f"Each section MUST have {bullets_per_sec} bullet points, each with 'text' and 'page_number' (integer).\n\n"
            f"Document Text:\n{text[:12000]}"
        )
        system = "You are an expert AI tutor helping students learn efficiently. Always return valid structured JSON summaries with section titles and page-referenced bullet points."

        try:
            data = await ollama_service.generate_json(prompt, system_prompt=system)
            raw_sections = data.get("sections", [])
            sections = []
            for sec in raw_sections:
                title = sec.get("title", "Key Concepts")
                bullets = sec.get("bullets", [])
                formatted_bullets = []
                for b in bullets:
                    if isinstance(b, dict):
                        formatted_bullets.append({
                            "text": str(b.get("text", "")),
                            "page_number": int(b.get("page_number", 1))
                        })
                    elif isinstance(b, str):
                        formatted_bullets.append({"text": b, "page_number": 1})

                if not formatted_bullets:
                    explanation = sec.get("explanation") or sec.get("key_points")
                    if isinstance(explanation, list):
                        formatted_bullets = [{"text": str(item), "page_number": 1} for item in explanation]
                    elif isinstance(explanation, str):
                        formatted_bullets = [{"text": explanation, "page_number": 1}]
                    else:
                        formatted_bullets = [{"text": "Key summary point", "page_number": 1}]

                sections.append({
                    "title": title,
                    "bullets": formatted_bullets
                })
        except Exception:
            sections = [
                {
                    "title": "Overview",
                    "bullets": [
                        {"text": text[:300] if text else "Document summary generated successfully.", "page_number": 1}
                    ]
                }
            ]

        record = {
            "id": str(uuid.uuid4()),
            "document_id": document_id,
            "sections": sections,
            "depth": depth,
            "disclaimer": SUMMARY_DISCLAIMER
        }

        _in_memory_summaries.append(record)

        try:
            res = supabase.table("summaries").insert(record).execute()
            if res.data:
                return res.data[0]
        except Exception:
            pass

        return record

    async def generate_summary(self, document_id: str, text: str, depth: SummaryDepth = SummaryDepth.QUICK) -> Dict[str, Any]:
        """Backwards compatibility wrapper."""
        return await self.generate_summary_for_text(document_id, text, depth=depth.value)

    async def get_latest_summary(self, document_id: str) -> Optional[Dict[str, Any]]:
        """Retrieves the most recent summary for a given document_id."""
        try:
            res = supabase.table("summaries").select("*").eq("document_id", document_id).order("created_at", desc=True).limit(1).execute()
            if res.data:
                return res.data[0]
        except Exception:
            pass

        doc_summaries = [s for s in _in_memory_summaries if s.get("document_id") == document_id]
        if doc_summaries:
            return doc_summaries[-1]

        return None

summary_service = SummaryService()
