import uuid
from typing import Any, Dict, List, Optional
from database import supabase
from models import SummaryDepth
from services.ollama_service import ollama_service

SUMMARY_DISCLAIMER = "Disclaimer: This summary was generated by AI locally. Please verify important details with source materials."

class SummaryService:
    """Service for generating and storing AI summaries using Ollama."""

    async def check_user_summary_quota(self, user_id: str) -> bool:
        """Verifies if user has remaining summary generations for current month."""
        try:
            res = supabase.table("user_usage").select("summary_generations_used").eq("user_id", user_id).execute()
            if res.data and res.data[0].get("summary_generations_used", 0) >= 50:
                return False
        except Exception:
            pass
        return True

    async def generate_summary(self, document_id: str, text: str, depth: SummaryDepth = SummaryDepth.QUICK) -> Dict[str, Any]:
        """Generates summary sections using Ollama LLM and saves to Supabase."""
        prompt = (
            f"Analyze the following document text and provide a structured JSON summary.\n"
            f"Depth level: {depth.value}\n"
            f"Format requirements:\n"
            f"Return a JSON object with a key 'sections' which is a list of objects containing:\n"
            f"- 'title': section heading\n"
            f"- 'key_points': list of main takeaway strings\n"
            f"- 'explanation': paragraph explaining concepts suitable for high school students\n\n"
            f"Document Text:\n{text[:8000]}"
        )
        system = "You are an expert AI tutor helping high school students learn efficiently. Keep summaries concise and clear."

        try:
            data = await ollama_service.generate_json(prompt, system_prompt=system)
            sections = data.get("sections", [
                {"title": "Overview", "key_points": ["Document uploaded successfully"], "explanation": text[:300]}
            ])
        except Exception:
            sections = [
                {"title": "Summary", "key_points": ["Key content summary"], "explanation": text[:500] if text else "No text extracted."}
            ]

        record = {
            "id": str(uuid.uuid4()),
            "document_id": document_id,
            "sections": sections,
            "depth": depth.value,
            "disclaimer": SUMMARY_DISCLAIMER
        }

        try:
            res = supabase.table("summaries").insert(record).execute()
            if res.data:
                return res.data[0]
        except Exception:
            pass

        return record

summary_service = SummaryService()
